[tool.poetry]
name = "deserialize"
version = "0.10.0"
description = "A library to make deserialization easy."

license = "MIT"

authors = [
    "Dale Myers <dale@myers.io>"
]

readme = 'README.md'

repository = "https://github.com/dalemyers/deserialize"
homepage = "https://github.com/dalemyers/deserialize"

keywords = ['deserialization', 'deserialize', 'objects', 'object', 'json']

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Topic :: Software Development :: Libraries"
]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
mypy = "=0.641"
pylint = "=2.1.1"
pytest = "=4.0.1"
pytest-cov = "=2.6.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
